create extension if not exists pgcrypto;

-- Sessões de reprodução (QoE por sessão)
create table if not exists public.playback_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  library_item_id text,
  title text,
  stream_mode text not null default 'browser',
  status text not null default 'started',
  startup_ms integer,
  watch_seconds integer not null default 0,
  rebuffer_count integer not null default 0,
  rebuffer_ms integer not null default 0,
  avg_bitrate_kbps integer,
  device text,
  network text,
  app_version text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_event_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists playback_sessions_user_started_idx
on public.playback_sessions (user_id, started_at desc);

create index if not exists playback_sessions_status_idx
on public.playback_sessions (status, started_at desc);

-- Eventos detalhados da sessão (buffering, erro, pause, etc)
create table if not exists public.playback_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.playback_sessions (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  event_type text not null,
  position_seconds numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists playback_events_session_idx
on public.playback_events (session_id, created_at desc);

create index if not exists playback_events_user_idx
on public.playback_events (user_id, created_at desc);

alter table public.playback_sessions enable row level security;
alter table public.playback_events enable row level security;

drop policy if exists "select_own_playback_sessions" on public.playback_sessions;
create policy "select_own_playback_sessions"
on public.playback_sessions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "insert_own_playback_sessions" on public.playback_sessions;
create policy "insert_own_playback_sessions"
on public.playback_sessions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "update_own_playback_sessions" on public.playback_sessions;
create policy "update_own_playback_sessions"
on public.playback_sessions
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "delete_own_playback_sessions" on public.playback_sessions;
create policy "delete_own_playback_sessions"
on public.playback_sessions
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "select_own_playback_events" on public.playback_events;
create policy "select_own_playback_events"
on public.playback_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "insert_own_playback_events" on public.playback_events;
create policy "insert_own_playback_events"
on public.playback_events
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "delete_own_playback_events" on public.playback_events;
create policy "delete_own_playback_events"
on public.playback_events
for delete
to authenticated
using (user_id = auth.uid());
